In [20]:
file = open("Inventory.txt","r")
print(file.readlines())
file.close()

['1,5 Star,5,0\n', '2,Milky Bar,5,95\n', '3,Cake,300,5\n', '4,Candy,1,200\n', '5,Chocolate,1,167\n']


In [17]:
file = open("Inventory.txt","a")
file.write("str")
file.close()

In [4]:
import numpy as geek
  
# input array
in_arr1 = geek.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1) 
  
in_arr2 = geek.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2) 
  
# Stacking the two arrays horizontally
out_arr = geek.stack((in_arr1, in_arr2), axis = 1)
print ("Output horizontally stacked array:\n ", out_arr)

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [[1 4]
 [2 5]
 [3 6]]
